apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::043902793737:role/eksctl-ksh-eks-nodegroup-ng-t3m-NodeInstanceRole-FEXtpeHfS17L
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    - userarn: arn:aws:iam::043902793737:user/Soloud-LWI
      username: soloud-lwi
      groups:
        - system:masters

