name: Build and Push WAS Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # -------------------------
      # Checkout app code repo
      # -------------------------
      - name: Checkout app repo
        uses: actions/checkout@v3

      # -------------------------
      # Docker Hub 로그인
      # -------------------------
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # -------------------------
      # Docker Build & Push
      # -------------------------
      - name: Build and push WAS image
        run: |
          WAS_IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/soloud-was
          WAS_TAG=${{ github.sha }}
          docker build -t $WAS_IMAGE:$WAS_TAG .
          docker push $WAS_IMAGE:$WAS_TAG

      # -------------------------
      # Checkout manifests repo
      # -------------------------
      - name: Checkout manifests repo
        uses: actions/checkout@v3
        with:
          repository: soloud1025/soloud-manifests
          token: ${{ secrets.GITHUB_TOKEN }}
          path: manifests

      # -------------------------
      # Update deployment.yaml
      # -------------------------
      - name: Update manifest image tag
        run: |
          WAS_IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/soloud-was
          WAS_TAG=${{ github.sha }}
          sed -i "s|image: .*|image: $WAS_IMAGE:$WAS_TAG|" manifests/k8s/deployment.yaml

      # -------------------------
      # Commit & Push manifests repo
      # -------------------------
      - name: Commit and push manifest changes
        run: |
          cd manifests
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add k8s/deployment.yaml
          git commit -m "Update WAS image to $WAS_TAG" || echo "No changes to commit"
          git push

