name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # =========================
      # Build & Push WAS Service
      # =========================
      - name: Build and push WAS image
        run: |
          WAS_IMAGE=dockerhubID/soloud-was
          WAS_TAG=${{ github.sha }}
          docker build -t $WAS_IMAGE:$WAS_TAG ./was
          docker push $WAS_IMAGE:$WAS_TAG

          # Update WAS manifest
          FILE=k8s/was/deployment.yaml
          sed -i "s|image: .*|image: $WAS_IMAGE:$WAS_TAG|" $FILE

      # =========================
      # Build & Push WEB Service
      # =========================
      - name: Build and push WEB image
        run: |
          WEB_IMAGE=dockerhubID/soloud-web
          WEB_TAG=${{ github.sha }}
          docker build -t $WEB_IMAGE:$WEB_TAG ./web
          docker push $WEB_IMAGE:$WEB_TAG

          # Update WEB manifest
          FILE=k8s/web/deployment.yaml
          sed -i "s|image: .*|image: $WEB_IMAGE:$WEB_TAG|" $FILE

      # =========================
      # Commit manifest changes
      # =========================
      - name: Commit and push manifest changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add k8s/was/deployment.yaml k8s/web/deployment.yaml
          git commit -m "Update WAS/WEB image tags to ${{ github.sha }}"
          git push

