name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write   # <-- push 허용 필요

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # =========================
      # Build & Push WAS
      # =========================
      - name: Build and push WAS image
        run: |
          WAS_IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/soloud-was
          WAS_TAG=${{ github.sha }}
          docker build -t $WAS_IMAGE:$WAS_TAG ./was
          docker push $WAS_IMAGE:$WAS_TAG
          sed -i "s|image: .*|image: $WAS_IMAGE:$WAS_TAG|" k8s/was/deployment.yaml

      # =========================
      # Build & Push WEB
      # =========================
      - name: Build and push WEB image
        run: |
          WEB_IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/soloud-web
          WEB_TAG=${{ github.sha }}
          docker build -t $WEB_IMAGE:$WEB_TAG ./web
          docker push $WEB_IMAGE:$WEB_TAG
          sed -i "s|image: .*|image: $WEB_IMAGE:$WEB_TAG|" k8s/web/deployment.yaml

      # =========================
      # Commit manifest changes
      # =========================
      - name: Commit and push manifest changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add k8s/was/deployment.yaml k8s/web/deployment.yaml
          git commit -m "Update WAS/WEB image tags to ${{ github.sha }}"
          git push

