name: Build and Push WAS Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write   # manifest 수정 후 push 허용

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # =========================
      # Build & Push WAS
      # =========================
      - name: Build and push WAS image
        run: |
          WAS_IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/soloud-was
          WAS_TAG=${{ github.sha }}
          docker build -t $WAS_IMAGE:$WAS_TAG .
          docker push $WAS_IMAGE:$WAS_TAG

          # Update WAS manifest
          sed -i "s|image: .*|image: $WAS_IMAGE:$WAS_TAG|" k8s/was/deployment.yaml

      # =========================
      # Commit manifest changes
      # =========================
      - name: Commit and push manifest changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add k8s/was/deployment.yaml
          git commit -m "Update WAS image to $WAS_TAG"
          git push

